exo1 : exo1.o logfile.o ezsem.o
	gcc -o exo1 exo1.o logfile.o ezsem.o
exo1.o : exo1.c
	gcc -c exo1.c -W -Wall
logfile.o : logfile.c
	gcc -c logfile.c -W -Wall
ezsem.o : ezsem.c
	gcc -c ezsem.c -W -Wall
